{
  "openapi": "3.0.0",
  "info": {
    "title": "sequelize-orm",
    "contact": {
      "name": "Doni Rahma Tiana",
      "email": "donirahmatiana@gmail.com"
    },
    "version": "1.0"
  },
  "servers": [
    {
      "url": "https://mighty-eyrie-29994.herokuapp.com"
    },
    {
      "url": "http://localhost:3000"
    }
  ],
  "paths": {
    "/": {
      "get": {
        "tags": ["Misc"],
        "summary": "Test RestfulAPI",
        "description": "Dummy RestfulAPI for testing if API is working or not.",
        "operationId": "TestRestfulAPI",
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    },
    "/api/auth/signup": {
      "post": {
        "tags": ["Misc"],
        "summary": "Signup",
        "description": "Register user's account.",
        "operationId": "Signup",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/SignupRequest"
              },
              "example": {
                "name": "doni",
                "username": "doni",
                "email": "doni@gmail.com",
                "password": "12345678",
                "passwordConfirmation": "12345678"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    },
    "/api/auth/signin": {
      "post": {
        "tags": ["Misc"],
        "summary": "Signin",
        "description": "Login user's account into system.",
        "operationId": "Signin",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/SigninRequest"
              },
              "example": {
                "username": "doni",
                "password": "12345678"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    },
    "/api/test/admin": {
      "get": {
        "tags": ["Misc"],
        "summary": "Admin page",
        "description": "This page is authorized for admin.",
        "operationId": "Adminpage",
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    },
    "/api/test/pm": {
      "get": {
        "tags": ["Misc"],
        "summary": "PM page",
        "description": "This page is authorized for Project Manager.",
        "operationId": "PMpage",
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    },
    "/api/test/user": {
      "get": {
        "tags": ["Misc"],
        "summary": "User page",
        "description": "This page is authorized for users.",
        "operationId": "Userpage",
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    },
    "/api/users": {
      "post": {
        "tags": ["Misc"],
        "summary": "Create user",
        "description": "Create a new user.",
        "operationId": "Createuser",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateuserRequest"
              },
              "example": {
                "name": "doni",
                "username": "doniAdmin",
                "email": "doniAdmin@gmail.com",
                "password": "12345678",
                "roles": ["ADMIN"]
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      },
      "get": {
        "tags": ["Misc"],
        "summary": "Read users",
        "description": "Get all users.",
        "operationId": "Readusers",
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false,
        "security": []
      }
    },
    "/api/users/11": {
      "put": {
        "tags": ["Misc"],
        "summary": "Update user",
        "description": "update user data with specifying id as request header.",
        "operationId": "Updateuser",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UpdateuserRequest"
              },
              "example": {
                "name": "doniAdmin"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      },
      "delete": {
        "tags": ["Misc"],
        "summary": "Delete user",
        "description": "delete a user with specifying id as request header.",
        "operationId": "Deleteuser",
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    },
    "/api/users/self": {
      "get": {
        "tags": ["Misc"],
        "summary": "Read self",
        "description": "Reading current user data.",
        "operationId": "Readself",
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    },
    "/api/users/10": {
      "get": {
        "tags": ["Misc"],
        "summary": "Read user",
        "description": "reading a user data with specifying id as request header.",
        "operationId": "Readuser",
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    },
    "/api/users/find-or-create": {
      "post": {
        "tags": ["Misc"],
        "summary": "Find or create user",
        "description": "Return user data if there is a match user, else create user.",
        "operationId": "Findorcreateuser",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/FindorcreateuserRequest"
              },
              "example": {
                "name": "rifaldi"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    },
    "/api/articles": {
      "post": {
        "tags": ["Misc"],
        "summary": "Create article",
        "description": "Create a new article.",
        "operationId": "Createarticle",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreatearticleRequest"
              },
              "example": {
                "title": "New Title",
                "content": "article content"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      },
      "get": {
        "tags": ["Misc"],
        "summary": "Read articles",
        "description": "Get all articles.",
        "operationId": "Readarticles",
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    },
    "/api/articles/1": {
      "put": {
        "tags": ["Misc"],
        "summary": "Update article",
        "description": "update an article with specifying id as request header if current user have authorization.",
        "operationId": "Updatearticle",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UpdatearticleRequest"
              },
              "example": {
                "title": "New Title Updated"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      },
      "delete": {
        "tags": ["Misc"],
        "summary": "Delete article",
        "description": "delete an article with specifying id as request header if user have authorization.",
        "operationId": "Deletearticle",
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    },
    "/api/articles/mine": {
      "get": {
        "tags": ["Misc"],
        "summary": "Read my article",
        "description": "Get all articles of current user.",
        "operationId": "Readmyarticle",
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    },
    "/api/articles/3": {
      "get": {
        "tags": ["Misc"],
        "summary": "Read article",
        "description": "Get an article with specifying id as request header.",
        "operationId": "Readarticle",
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    },
    "/api/articles/find-or-create": {
      "post": {
        "tags": ["Misc"],
        "summary": "Find or create article",
        "description": "Return an article if there is a match data, else create article.",
        "operationId": "Findorcreatearticle",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/FindorcreatearticleRequest"
              },
              "example": {
                "title": "New Title From Admin"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    }
  },
  "components": {
    "schemas": {
      "SignupRequest": {
        "title": "SignupRequest",
        "required": [
          "name",
          "username",
          "email",
          "password",
          "passwordConfirmation"
        ],
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "username": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          },
          "passwordConfirmation": {
            "type": "string"
          }
        },
        "example": {
          "name": "doni",
          "username": "doni",
          "email": "doni@gmail.com",
          "password": "12345678",
          "passwordConfirmation": "12345678"
        }
      },
      "SigninRequest": {
        "title": "SigninRequest",
        "required": ["username", "password"],
        "type": "object",
        "properties": {
          "username": {
            "type": "string"
          },
          "password": {
            "type": "string"
          }
        },
        "example": {
          "username": "doni",
          "password": "12345678"
        }
      },
      "CreateuserRequest": {
        "title": "CreateuserRequest",
        "required": ["name", "username", "email", "password", "roles"],
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "username": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          },
          "roles": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": ""
          }
        },
        "example": {
          "name": "doni",
          "username": "doniAdmin",
          "email": "doniAdmin@gmail.com",
          "password": "12345678",
          "roles": ["ADMIN"]
        }
      },
      "UpdateuserRequest": {
        "title": "UpdateuserRequest",
        "required": ["name"],
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          }
        },
        "example": {
          "name": "doniAdmin"
        }
      },
      "FindorcreateuserRequest": {
        "title": "FindorcreateuserRequest",
        "required": ["name"],
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          }
        },
        "example": {
          "name": "rifaldi"
        }
      },
      "CreatearticleRequest": {
        "title": "CreatearticleRequest",
        "required": ["title", "content"],
        "type": "object",
        "properties": {
          "title": {
            "type": "string"
          },
          "content": {
            "type": "string"
          }
        },
        "example": {
          "title": "New Title",
          "content": "article content"
        }
      },
      "UpdatearticleRequest": {
        "title": "UpdatearticleRequest",
        "required": ["title"],
        "type": "object",
        "properties": {
          "title": {
            "type": "string"
          }
        },
        "example": {
          "title": "New Title Updated"
        }
      },
      "FindorcreatearticleRequest": {
        "title": "FindorcreatearticleRequest",
        "required": ["title"],
        "type": "object",
        "properties": {
          "title": {
            "type": "string"
          }
        },
        "example": {
          "title": "New Title From Admin"
        }
      }
    },
    "securitySchemes": {
      "httpBearer": {
        "type": "http",
        "scheme": "bearer"
      }
    }
  },
  "security": [
    {
      "httpBearer": []
    }
  ],
  "tags": [
    {
      "name": "Misc",
      "description": ""
    }
  ]
}
