{
  "openapi": "3.0.0",
  "info": {
    "title": "CRUD Restful API using Sequelize and Swagger",
    "description": "CMS CRUD Restful API with authentication and authorization. Using PostgreSQL as DBMS and Sequelize as its ORM. Documentation is served using Swagger.",
    "contact": {
      "name": "Doni Rahma Tiana",
      "email": "donirahmatiana@gmail.com"
    },
    "license": {
      "name": "ISC",
      "url": "https://opensource.org/licenses/ISC"
    },
    "version": "1.0"
  },
  "servers": [
    {
      "url": "https://mighty-eyrie-29994.herokuapp.com",
      "description": "Production server"
    },
    {
      "url": "http://localhost:3000",
      "description": "Development server"
    }
  ],
  "paths": {
    "/api/auth/signup": {
      "post": {
        "tags": ["Public"],
        "summary": "Signup",
        "description": "Register user's account.",
        "operationId": "Signup",
        "consumes": ["application/json"],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/SignupRequest"
              },
              "example": {
                "name": "doni",
                "username": "doni",
                "email": "doni@gmail.com",
                "password": "12345678",
                "passwordConfirmation": "12345678"
              }
            }
          },
          "required": true
        },
        "responses": {
          "201": {
            "description": "account successfully registered"
          },
          "400": {
            "description": "required request body is missing, does not meet standards, or duplicate account were found"
          },
          "500": {
            "description": "server error"
          }
        },
        "deprecated": false
      }
    },
    "/api/auth/signin": {
      "post": {
        "tags": ["Public"],
        "summary": "Signin",
        "description": "Login user's account into system.",
        "operationId": "Signin",
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/SigninRequest"
              },
              "example": {
                "username": "admin",
                "password": "12345678"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "login success"
          },
          "400": {
            "description": "required request body is missing or does not meet standards"
          },
          "401": {
            "description": "invalid password"
          },
          "404": {
            "description": "user not found"
          },
          "500": {
            "description": "server error"
          }
        },
        "deprecated": false
      }
    },
    "/api/test/admin": {
      "get": {
        "tags": ["Admin"],
        "summary": "Admin page",
        "description": "This page is authorized for admin.",
        "operationId": "AdminPage",
        "security": [
          {
            "httpBearer": []
          }
        ],
        "responses": {
          "200": {
            "description": "authentication as admin success"
          },
          "403": {
            "description": "no token provided"
          },
          "500": {
            "description": "authentication failed"
          }
        },
        "deprecated": false
      }
    },
    "/api/test/pm": {
      "get": {
        "tags": ["PM"],
        "summary": "PM page",
        "description": "This page is authorized for Project Manager.",
        "operationId": "PmPage",
        "security": [
          {
            "httpBearer": []
          }
        ],
        "responses": {
          "200": {
            "description": "authentication as PM success"
          },
          "403": {
            "description": "no token provided"
          },
          "500": {
            "description": "authentication failed"
          }
        },
        "deprecated": false
      }
    },
    "/api/test/user": {
      "get": {
        "tags": ["User"],
        "summary": "User page",
        "description": "This page is authorized for users.",
        "operationId": "UserPage",
        "security": [
          {
            "httpBearer": []
          }
        ],
        "responses": {
          "200": {
            "description": "authentication as user success"
          },
          "403": {
            "description": "no token provided"
          },
          "500": {
            "description": "authentication failed"
          }
        },
        "deprecated": false
      }
    },
    "/api/users": {
      "post": {
        "tags": ["Admin"],
        "summary": "Create user",
        "description": "Create a new user.",
        "operationId": "CreateUser",
        "security": [
          {
            "httpBearer": []
          }
        ],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateUserRequest"
              },
              "example": {
                "name": "doniPM",
                "username": "doniPM",
                "email": "doniPM@gmail.com",
                "password": "12345678",
                "roles": ["PM"]
              }
            }
          },
          "required": true
        },
        "responses": {
          "201": {
            "description": "user created"
          },
          "400": {
            "description": "required request body is missing, does not meet standards, or duplicate account were found"
          },
          "403": {
            "description": "no token provided or not an admin"
          },
          "500": {
            "description": "authentication failed or server error"
          }
        },
        "deprecated": false
      },
      "get": {
        "tags": ["Public", "Admin", "PM", "User"],
        "summary": "Read users",
        "description": "Get all users.",
        "operationId": "ReadUsers",
        "responses": {
          "200": {
            "description": "read users success"
          },
          "500": {
            "description": "server error"
          }
        },
        "deprecated": false
      }
    },
    "/api/users/{user_id}": {
      "get": {
        "tags": ["Public", "Admin", "PM", "User"],
        "summary": "Read user",
        "description": "reading a user data with specifying id as request header.",
        "operationId": "ReadUser",
        "parameters": [
          {
            "in": "path",
            "name": "user_id",
            "required": true,
            "description": "id of a user",
            "schema": {
              "type": "integer",
              "minimum": 1
            }
          }
        ],
        "responses": {
          "200": {
            "description": "read user detail success"
          },
          "400": {
            "description": "no param id provided"
          },
          "404": {
            "description": "user not found"
          },
          "500": {
            "description": "server error"
          }
        },
        "deprecated": false
      },
      "put": {
        "tags": ["Admin", "Owner"],
        "summary": "Update user",
        "description": "update user data with specifying id as request header.",
        "operationId": "UpdateUser",
        "parameters": [
          {
            "in": "path",
            "name": "user_id",
            "required": true,
            "description": "id of a user",
            "schema": {
              "type": "integer",
              "minimum": 1
            }
          }
        ],
        "security": [
          {
            "httpBearer": []
          }
        ],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UpdateUserRequest"
              },
              "example": {
                "name": "doni PM",
                "username": "DoniPM",
                "email": "doniiPM@gmail.com",
                "password": "donipm$$"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "user updated"
          },
          "400": {
            "description": "no param id provided, required request body is missing, does not meet standards, duplicate account were found, or intended to delete superadmin"
          },
          "403": {
            "description": "no token provided, not an admin, or not an owner"
          },
          "500": {
            "description": "authentication failed or server error"
          }
        },
        "deprecated": false
      },
      "delete": {
        "tags": ["Admin", "Owner"],
        "summary": "Delete user",
        "description": "delete a user with specifying id as request header.",
        "operationId": "DeleteUser",
        "parameters": [
          {
            "in": "path",
            "name": "user_id",
            "required": true,
            "description": "id of a user",
            "schema": {
              "type": "integer",
              "minimum": 1
            }
          }
        ],
        "security": [
          {
            "httpBearer": []
          }
        ],
        "responses": {
          "200": {
            "description": "user deleted"
          },
          "400": {
            "description": "no param id provided or intended to delete superadmin"
          },
          "403": {
            "description": "no token provided, not an admin, or not an owner"
          },
          "500": {
            "description": "authentication failed or server error"
          }
        },
        "deprecated": false
      }
    },
    "/api/users/self": {
      "get": {
        "tags": ["Admin", "PM", "User", "Owner"],
        "summary": "Read self",
        "description": "Reading current user data.",
        "operationId": "ReadSelf",
        "security": [
          {
            "httpBearer": []
          }
        ],
        "responses": {
          "200": {
            "description": "read self account detail success"
          },
          "403": {
            "description": "no token provided"
          },
          "404": {
            "description": "user not found"
          },
          "500": {
            "description": "server error"
          }
        },
        "deprecated": false
      }
    },
    "/api/articles": {
      "post": {
        "tags": ["Admin", "PM", "User"],
        "summary": "Create article",
        "description": "Create a new article.",
        "operationId": "CreateArticle",
        "security": [
          {
            "httpBearer": []
          }
        ],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateArticleRequest"
              },
              "example": {
                "title": "New Admin's Title",
                "content": "article content"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      },
      "get": {
        "tags": ["Public", "Admin", "PM", "User"],
        "summary": "Read articles",
        "description": "Get all articles.",
        "operationId": "ReadArticles",
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    },
    "/api/articles/mine": {
      "get": {
        "tags": ["Admin", "PM", "User", "Owner"],
        "summary": "Read my article",
        "description": "Get all articles of current user.",
        "operationId": "ReadMyArticle",
        "security": [
          {
            "httpBearer": []
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    },
    "/api/articles/{article_id}": {
      "get": {
        "tags": ["Public", "Admin", "PM", "User"],
        "summary": "Read article",
        "description": "Get an article with specifying id as request header.",
        "operationId": "ReadArticle",
        "parameters": [
          {
            "in": "path",
            "name": "article_id",
            "required": true,
            "description": "id of an article",
            "schema": {
              "type": "integer",
              "minimum": 1
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      },
      "put": {
        "tags": ["Admin", "Owner"],
        "summary": "Update article",
        "description": "update an article with specifying id as request header if current user have authorization.",
        "operationId": "UpdateArticle",
        "parameters": [
          {
            "in": "path",
            "name": "article_id",
            "required": true,
            "description": "id of an article",
            "schema": {
              "type": "integer",
              "minimum": 1
            }
          }
        ],
        "security": [
          {
            "httpBearer": []
          }
        ],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UpdateArticleRequest"
              },
              "example": {
                "title": "New Title Updated"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      },
      "delete": {
        "tags": ["Admin", "Owner"],
        "summary": "Delete article",
        "description": "delete an article with specifying id as request header if user have authorization.",
        "operationId": "DeleteArticle",
        "parameters": [
          {
            "in": "path",
            "name": "article_id",
            "required": true,
            "description": "id of an article",
            "schema": {
              "type": "integer",
              "minimum": 1
            }
          }
        ],
        "security": [
          {
            "httpBearer": []
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    },
    "/api/comments/{article_id}": {
      "post": {
        "tags": ["Admin", "PM", "User"],
        "summary": "Create comment",
        "description": "Create a new comment based on an article",
        "operationId": "CreateComment",
        "parameters": [
          {
            "in": "path",
            "name": "article_id",
            "required": true,
            "description": "id of an article",
            "schema": {
              "type": "integer",
              "minimum": 1
            }
          }
        ],
        "security": [
          {
            "httpBearer": []
          }
        ],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateCommentRequest"
              },
              "example": {
                "content": "pertamax"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false,
        "servers": [
          {
            "url": "http://localhost:3000/api/comments",
            "variables": {}
          }
        ]
      },
      "get": {
        "tags": ["Public", "Admin", "PM", "User"],
        "summary": "Read comments",
        "description": "Read comments based on an article",
        "operationId": "ReadComments",
        "parameters": [
          {
            "in": "path",
            "name": "article_id",
            "required": true,
            "description": "id of an article",
            "schema": {
              "type": "integer",
              "minimum": 1
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false,
        "servers": [
          {
            "url": "http://localhost:3000/api/comments",
            "variables": {}
          }
        ]
      }
    },
    "/api/comments/{comment_id}": {
      "put": {
        "tags": ["Admin", "Owner"],
        "summary": "Update comment",
        "description": "Update a comment of an article",
        "operationId": "UpdateComment",
        "parameters": [
          {
            "in": "path",
            "name": "comment_id",
            "required": true,
            "description": "id of an comment",
            "schema": {
              "type": "integer",
              "minimum": 1
            }
          }
        ],
        "security": [
          {
            "httpBearer": []
          }
        ],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UpdateCommentRequest"
              },
              "example": {
                "content": "premium"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false,
        "servers": [
          {
            "url": "http://localhost:3000/api/comments",
            "variables": {}
          }
        ]
      },
      "delete": {
        "tags": ["Admin"],
        "summary": "Delete comment",
        "description": "Delete a comment of an article for admin role",
        "operationId": "DeleteComment",
        "parameters": [
          {
            "in": "path",
            "name": "comment_id",
            "required": true,
            "description": "id of an comment",
            "schema": {
              "type": "integer",
              "minimum": 1
            }
          }
        ],
        "security": [
          {
            "httpBearer": []
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false,
        "servers": [
          {
            "url": "http://localhost:3000/api/comments",
            "variables": {}
          }
        ]
      }
    }
  },
  "components": {
    "schemas": {
      "SignupRequest": {
        "title": "SignupRequest",
        "required": [
          "name",
          "username",
          "email",
          "password",
          "passwordConfirmation"
        ],
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "username": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          },
          "passwordConfirmation": {
            "type": "string"
          }
        },
        "example": {
          "name": "doni",
          "username": "doni",
          "email": "doni@gmail.com",
          "password": "12345678",
          "passwordConfirmation": "12345678"
        }
      },
      "SigninRequest": {
        "title": "SigninRequest",
        "required": ["username", "password"],
        "type": "object",
        "properties": {
          "username": {
            "type": "string"
          },
          "password": {
            "type": "string"
          }
        },
        "example": {
          "username": "admin",
          "password": "12345678"
        }
      },
      "CreateUserRequest": {
        "title": "CreateUserRequest",
        "required": ["name", "username", "email", "password"],
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "username": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          },
          "roles": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "roles element can be either ADMIN, PM, or USER"
          }
        },
        "example": {
          "name": "doniPM",
          "username": "doniPM",
          "email": "doniPM@gmail.com",
          "password": "12345678",
          "roles": ["PM"]
        }
      },
      "UpdateUserRequest": {
        "title": "UpdateUserRequest",
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "username": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          }
        },
        "example": {
          "name": "Updated Doni PM",
          "username": "updatedDoniPM",
          "email": "updatedDoniPM@gmail.com",
          "password": "updateddonipm"
        }
      },
      "CreateArticleRequest": {
        "title": "CreateArticleRequest",
        "required": ["title", "content"],
        "type": "object",
        "properties": {
          "title": {
            "type": "string"
          },
          "content": {
            "type": "string"
          }
        },
        "example": {
          "title": "Article Title",
          "content": "Article content"
        }
      },
      "UpdateArticleRequest": {
        "title": "UpdateArticleRequest",
        "type": "object",
        "properties": {
          "title": {
            "type": "string"
          },
          "content": {
            "type": "string"
          }
        },
        "example": {
          "title": "Updated Article Title",
          "content": "Updated article content"
        }
      },
      "CreateCommentRequest": {
        "title": "CreateCommentRequest",
        "required": ["content"],
        "type": "object",
        "properties": {
          "content": {
            "type": "string"
          }
        },
        "example": {
          "content": "pertamax"
        }
      },
      "UpdateCommentRequest": {
        "title": "UpdateCommentRequest",
        "required": ["content"],
        "type": "object",
        "properties": {
          "content": {
            "type": "string"
          }
        },
        "example": {
          "content": "premium"
        }
      }
    },
    "securitySchemes": {
      "httpBearer": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  },
  "tags": [
    {
      "name": "Public",
      "description": "clients without account"
    },
    {
      "name": "Admin",
      "description": "clients with admin role"
    },
    {
      "name": "PM",
      "description": "clients with PM role"
    },
    {
      "name": "User",
      "description": "clients with user role"
    },
    {
      "name": "Owner",
      "description": "clients with authorization of some actions"
    }
  ]
}
